name: water_atm_demo
description: Water ATM API demo for managing cashles topup.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  aquedart: ^5.0.4
    # path: /home/genius/Documents/dart_packages/aquedart/aquedart
    # git:
    #   url: git://github.com/EddieKamau/aquedart.git
    #   path: aquedart

  phantom_model_manager:
    # path: /home/genius/Documents/phantom/shared/phantom_model_manager
    git:
      url: git@github.com:EddieKamau/phantom_wallet_shared.git
      path: phantom_model_manager

  phantom_process_response:
    # path: /home/genius/Documents/phantom/shared/phantom_process_response
    git:
      url: git@github.com:EddieKamau/phantom_wallet_shared.git
      path: phantom_process_response

dev_dependencies:
  aquedart_test: ^3.0.0